#!/bin/bash
# query_suburbs - Run a Query on the suburbs.sqlite database
# Usage: query_suburbs
# For debugging, uncomment the following line
# set -euxo pipefail
# todo:

cd $HOME

# Ask for a place name or postal code

function run_query() {
  # See how many results for response treated as a postal code
  query="SELECT COUNT(id) FROM locality WHERE"
  query="$query postal_code = '$1';"
  result=$(sqlite3 $HOME/suburbs.sqlite "$query" 2>/dev/null)
  # If none, then search as a place name
  if [ "$result" == "0" ]; then
    query="SELECT postal_code as 'Post Code', "
    query="$query place_name as 'Place Name', "
    query="$query admin_code1 as 'State' FROM locality WHERE"
    query="$query lower(place_name) = lower('$1');"
    result=$(sqlite3 $HOME/suburbs.sqlite "$query" -markdown 2>/dev/null)
    # If none, try to find a match that begins with the search term
    if [ "$result" == "" ]; then
      query="SELECT postal_code as 'Post Code', "
      query="$query place_name as 'Place Name', "
      query="$query admin_code1 as 'State' FROM locality WHERE"
      query="$query lower(place_name) like lower('$1%');"
      result=$(sqlite3 $HOME/suburbs.sqlite "$query" -markdown 2>/dev/null)
      if [ "$result" == "" ]; then
        echo "No match found for '$1'"
        return
      else
        echo "$result"
      fi
    else
      echo "$result"
    fi
  else
    query="SELECT postal_code as 'Post Code', "
    query="$query place_name as 'Place Name', "
    query="$query admin_code1 as 'State' FROM locality WHERE"
    query="$query postal_code = '$1';"
    result=$(sqlite3 $HOME/suburbs.sqlite "$query" -markdown 2>/dev/null)
    if [ "$result" == "" ]; then
      echo "No match found for '$1'"
      return
    else
      echo "$result"
    fi
  fi
}

# Loop until the user quits
while true; do
    clear

    read -p "Enter a Place Name or Postcode (q to quit): " choice
    case $choice in
        q|Q)
            break
            ;;
        *)
            run_query "$choice"
            read -p "Press any key to continue..."
            ;;
    esac
done
