#!/bin/bash
# query_suburbs - Run a Query on the suburbs.sqlite database
# Usage: query_suburbs
# For debugging, uncomment the following line
# set -euxo pipefail
# todo:

cd $HOME

# Ask for a place name or postal code

function run_query() {
  basequery="SELECT postal_code, place_name, admin_code1 FROM locality WHERE "
  # See how many results for response treated as a postal code
  query="SELECT COUNT(id) FROM locality WHERE"
  query="$query postal_code = '$1';"
  result=$(sqlite3 $HOME/suburbs.sqlite "$query" 2>/dev/null)
  # If none, then search as a place name or part thereof
  if [ "$result" == "0" ]; then
    query="$basequery lower(place_name) like lower('%$1%');"
    result=$(sqlite3 $HOME/suburbs.sqlite "$query" -box 2>/dev/null)
    if [ "$result" == "" ]; then
        echo "No match found for '$1'"
        return
    else
      echo "$result"
    fi
  else
    query="$basequery postal_code = '$1';"
    result=$(sqlite3 $HOME/suburbs.sqlite "$query" -box 2>/dev/null)
    echo "$result"
  fi # $result == "0"
}

# Loop until the user quits
while true; do
    clear

    read -p "Enter a Place Name or Postcode (q to quit): " choice
    case $choice in
        q|Q)
            break
            ;;
        *)
            run_query "$choice"
            read -p "Press <Enter> to continue..."
            ;;
    esac
done
